redirectsOrigin = "config"
plugins = []
headers = []

[dev]
command = "npm run dev"
port = 3000

[functions]

  [functions."*"]

[build]
  command = "npm run build"
  publish = "dist"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]